<?xml version="1.0" encoding="utf-8"?><Database Name="HumaneSociety" Class="HumaneSocietyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-RG5MV00;Initial Catalog=HumaneSociety;Integrated Security=True" SettingsObjectName="HumaneSociety.Properties.Settings" SettingsPropertyName="HumaneSocietyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Adopter" Member="Adopters">
    <Type Name="Adopter">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="CriminalRecords" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Hobbies" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cat" Member="Cats">
    <Type Name="Cat">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Breed" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AdoptionStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TypeOfFood" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AmountOfFoodNeeded" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ShotStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RoomNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dog" Member="Dogs">
    <Type Name="Dog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Breed" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AdoptionStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TypeOfFood" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AmountOfFoodNeeded" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ShotStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RoomNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfHire" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Jobtitle" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="WorkStatus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>